import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import PrivyProviderWrapper from '@/providers/privy'
import ApolloProviderWrapper from '@/providers/apollo'
import StoreProvider from '@/providers/store'
import { AuthProvider } from '@/providers/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PrivyProviderWrapper>
          <StoreProvider>
            <AuthProvider>
              <ApolloProviderWrapper>{children}</ApolloProviderWrapper>
            </AuthProvider>
          </StoreProvider>
        </PrivyProviderWrapper>
      </body>
    </html>
  )
}
