name: CI

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  Test:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: pnpm lint

      - name: Check formatting
        run: pnpm format

  Docker-Push:
    runs-on: 'ubuntu-latest'
    needs: Test
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      packages: write
      contents: read
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Login to ghcr.io
        run: docker login ghcr.io -u aarontravass --password '${{ secrets.GITHUB_TOKEN }}'

      - name: Build platform image
        run: docker build -t ghcr.io/aarontravass/medihacks2024-platform:${{github.sha}} --target platform .

      - name: Push platform image to ghcr.io
        run: docker push ghcr.io/aarontravass/medihacks2024-platform:${{github.sha}}

      - name: Notify Render for platform deploy
        run: curl -G --data-urlencode "imgURL=ghcr.io/aarontravass/medihacks2024-platform:${{github.sha}}"  ${{secrets.RENDER_DEPLOY_HOOK_URL}}

      - name: Build upload image
        run: docker build -t ghcr.io/aarontravass/medihacks2024-upload:${{github.sha}} --target upload .

      - name: Push upload image to ghcr.io
        run: docker push ghcr.io/aarontravass/medihacks2024-upload:${{github.sha}}

      - name: Notify Render for upload deploy
        run: curl -G --data-urlencode "imgURL=ghcr.io/aarontravass/medihacks2024-upload:${{github.sha}}"  ${{secrets.RENDER_UPLOAD_DEPLOY_HOOK_URL}}
