name: CI

on: 
  pull_request:
    branches: ['main']

jobs:
  Test:
    runs-on: 'ubuntu-latest'
    steps:

      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: pnpm lint

      - name: Check formatting
        run: pnpm format

